name: pw
description: "App Pw"

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 #
  flutter_launcher_icons: ^0.14.4
  flutter_bluetooth_serial:
    path: lib_plugins/flutter_bluetooth_serial


  android_intent_plus: ^5.3.1
  flutter_blue_plus: ^1.35.3
  permission_handler: ^12.0.1
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5

  shared_preferences: ^2.5.0
  path_provider: ^2.1.5
  get: ^4.7.2
  url_launcher: ^6.3.1
  device_preview: ^1.2.0
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/logo_pw.png"
  adaptive_icon_foreground: "assets/images/logo/logo_pw.png"
  adaptive_icon_background: "assets/images/logo/logo_pw.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: PWSeriesFont
      fonts:
        - asset: assets/fonts/PwSeries.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Roboto-bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

  assets:
    - assets/images/
    - assets/images/desarrollado_por/
    - assets/images/temas/
    - assets/images/idiomas/
    - assets/images/tecladoPw/
    - assets/images/tecladoPw/botones/
    - assets/images/tecladoPw/botones/On/
    - assets/images/tecladoPw/botones/Off/
    - assets/images/tecladoPw/fondo/
    - assets/images/iconos/
    - assets/images/teclado_pin/
    - assets/images/demo/
    - assets/images/Botones/
    - assets/images/Botones/Espanol/
    - assets/images/Botones/Frances/
    - assets/images/Botones/Ingles/
    - assets/images/Botones/Portugues/
    - assets/images/configuracion_avanzada/
    - assets/images/configuracion_teclado/
    - assets/images/drawer/
    - assets/images/header/
    - assets/images/logo/
    - assets/images/splash_screens/

    - assets/audios/
    - assets/audios/sirena/
    - assets/audios/wail/
    - assets/audios/horn/